### ISSUE TITLE
Ask timed out on DnsServiceLocator

### ISSUE THREAD

**Issue by GervaisYO** [typesafehub/service-locator-dns#31]
Hi here,

i'm having some trouble with the library service-locator-dns. I'm using following version of the library: `"com.lightbend" %% "lagom14-scala-service-locator-dns" % "2.3.0"` with lagom version 1.4.1.

When deploying my lagom service to a kubernetes cluster, i'm getting the following error:
```
[error] a.a.OneForOneStrategy - Ask timed out on [Actor[akka://authenticationservice/user/DnsServiceLocator#1057488938]] after [4000 ms]. Sender[null] sent message of type "com.lightbend.dns.locator.ServiceLocator$GetAddress".
akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://authenticationservice/user/DnsServiceLocator#1057488938]] after [4000 ms]. Sender[null] sent message of type "com.lightbend.dns.locator.ServiceLocator$GetAddress".
	at akka.pattern.PromiseActorRef$.$anonfun$defaultOnTimeout$1(AskSupport.scala:595)
	at akka.pattern.PromiseActorRef$.$anonfun$apply$1(AskSupport.scala:605)
	at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:140)
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:866)
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:109)
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:103)
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:864)
	at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:328)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:279)
	at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:283)
```

I'm investigating on this issue for some time already and i don't understand what the problem is.
Any Ideas on what the problem is?

**Comment by kolemannix** [comment]
I am encountering the same issue and having a lot of trouble finding the cause. Definitely could be my configuration, which I have not been able to validate since this error is all I'm getting.

**Comment by Voltir** [comment]
I ran into a similar issue when stopping and restarting a minikube instance running a copy of the lagom chirper sample project.

**Comment by GervaisYO** [comment]
I ran into that Problem as well. The problem for me was not related to any Lagom configuration, but to a wrong configuration of my kubernetes Cluster.
The Network Pod was wrongly configured et so dns resolution did not work inside the cluster
